
name: Clone Public Repository Workflow

on:
  push:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
    
  job-public-repo-ubuntu:
    runs-on: ubuntu-latest
    steps:
      
      - name: Clone a02-trial BR_kernel_a02 repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'a02-trial'
          repository: 'BR_kernel_a02'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          ls -la
        shell: bash
